:PROPERTIES:
:ID:       607bc8ec-f64c-4ea9-bc48-b3ff82fb9934
:END:
#+TITLE: org-preview-html
#+SUBTITLE:
#+AUTHOR: David7ce
#+CREATED: [2022-07-23 Wed 19:07]
#+LAST_MODIFIED: [2021-10-25 Mon 18:57:31]
#+FILETAGS: :blog:
#+OPTIONS: num:nil toc:nil ^:{} 

Alright so this is just a first post testing the features of this system. My old blog had nothing on it and this one probably has nothing on it either. If I can figure out how to publish [[id:ef93dff4-b19f-4835-9002-9d4215f8a6fe][Org-mode]] files properly, I'll actually trying writing stuff again. I do have a bunch of drafts. Just nothing /concrete/...

[[http://melpa.org/packages/org-preview-html-badge.svg]]

[[#usage][Usage]]

* Installation
** MELPA
~M-x package-install org-preview-html~.
      
* Demo
This demo is using the =xwidget= browser. The author suggests utilizing the =xwidget= browser, though =eww= is set as default for the comfort of past users.
![][https://raw.githubusercontent.com/jakebox/org-preview-html/master/org-preview-html-demo.gif]

* Limitations
It should be noted that as of now =org-preview-html-mode= officially supports previewing only one buffer at a time. Any suggestions on how previewing multiple buffers would work are welcome. It would be fairly trivial to implement preview support without any nice automatic switching/saving features; however, I would rather implement a smooth, pleasant experience rather than a janky one.

* Todos
+ Improve ~instant~ mode
+ Auto-jump to current position in preview


Press key for an agenda command
-------------------------------
a Agenda for the current week or day
t List of all TODO entries

#+TAGS: { @OFFICE(o) @HOME(h) } COMPUTER(c) PHONE(p) READING(r)


Inherited:
Current:
{ [o] @OFFICE     [h] @HOME    }
  [C] COMPUTER   [p] PHONE   [r] READING


** Lord of the Rings
   My favorite scenes are (in this order)
   1. The attack of the Rohirrim
   2. Eowyn's fight with the witch king
      + this was already my favorite scene in the book
      + I really like Miranda Otto.
   3. Peter Jackson being shot by Legolas
       - on DVD only
      He makes a really funny face when it happens.
   But in the end, no individual scenes matter but the film as a whole.
   Important actors in this film are:
   - Elijah Wood :: He plays Frodo
   - Sean Austin :: He plays Sam, Frodo's friend.  I still remember
     him very well from his role as Mikey Walsh in The Goonies.
